# Generated by Django 3.1.4 on 2021-01-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(default='Wow this is Cool!')),
            ],
        ),
        migrations.DeleteModel(
            name='Darse',
        ),
    ]
